InjectionTk.cpp: pass proper variadic function argument
Compiling with clang leads to this error.

    $ make BUILD_VERBOSE=1 CC=clang CXX=clang++
    clang++ -DLIB_NAME=\"vastpreload\" -DLIB_VERSION=\"1.0-3\" -DBOOST_SPIRIT_THREADSAFE -D_GNU_SOURCE -I ./source -Wunused-variable -Woverloaded-virtual -Wextra -Wno-unused-parameter -fmessage-length=0 -fno-strict-aliasing -pthread -ggdb -std=c++14 -fPIC -O3 -Wuninitialized  -c source/InjectionTk.cpp -E -MMD -MFsource/InjectionTk.d -MTsource/InjectionTk.o -o/dev/null
    clang++ -DLIB_NAME=\"vastpreload\" -DLIB_VERSION=\"1.0-3\" -DBOOST_SPIRIT_THREADSAFE -D_GNU_SOURCE -I ./source -Wunused-variable -Woverloaded-virtual -Wextra -Wno-unused-parameter -fmessage-length=0 -fno-strict-aliasing -pthread -ggdb -std=c++14 -fPIC -O3 -Wuninitialized  -o source/InjectionTk.o -c source/InjectionTk.cpp
    source/InjectionTk.cpp:125:50: error: cannot pass object of non-trivial type 'std::string' (aka 'basic_string<char>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
                                            "dirfd: %d; fd: %d; path: %s\n", dirfd, fd, path);
                                                                                        ^
    1 error generated.
    make: *** [Makefile:88: source/InjectionTk.o] Error 1