Interceptors.cpp: don't use '/*' inside of a comment
Compiling with clang, -Wall, and -Werror, leads to the following error.

    $ make BUILD_VERBOSE=1 CC=clang CXX=clang++
    clang++ -DLIB_NAME=\"vastpreload\" -DLIB_VERSION=\"1.0-3\" -DBOOST_SPIRIT_THREADSAFE -D_GNU_SOURCE -I ./source -Wunused-variable -Woverloaded-virtual -Wextra -Wno-unused-parameter -fmessage-length=0 -fno-strict-aliasing -pthread -ggdb -std=c++14 -fPIC -O3 -Wuninitialized -Wall -Werror  -c source/Interceptors.cpp -E -MMD -MFsource/Interceptors.d -MTsource/Interceptors.o -o/dev/null
    source/Interceptors.cpp:9:24: error: '/*' within block comment [-Werror,-Wcomment]
     *              $ ls -lh /some/dir/*
                                      ^
    1 error generated.
    make: *** [Makefile:87: source/Interceptors.o] Error 1